'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSLayoutFacturacionModerna

  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"), _
   System.ServiceModel.ServiceContractAttribute([Namespace]:="https://t1demo.facturacionmoderna.com/timbrado/soap", ConfigurationName:="WSLayoutFacturacionModerna.Timbrado_ManagerPort")> _
  Public Interface Timbrado_ManagerPort

    <System.ServiceModel.OperationContractAttribute(Action:="https://t1demo.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=True, Use:=System.ServiceModel.OperationFormatUse.Encoded)> _
    Function requestTimbrarCFDI(ByVal request As RequestTimbrarCFDI) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Object

    <System.ServiceModel.OperationContractAttribute(Action:="https://t1demo.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction:="*"), _
     System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=True, Use:=System.ServiceModel.OperationFormatUse.Encoded)> _
    Function requestCancelarCFDI(ByVal request As RequestCancelarCFDI) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Object
  End Interface

  <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
  Public Interface Timbrado_ManagerPortChannel
    Inherits WSLayoutFacturacionModerna.Timbrado_ManagerPort, System.ServiceModel.IClientChannel
  End Interface

  <System.Diagnostics.DebuggerStepThroughAttribute(), _
   System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
  Partial Public Class Timbrado_ManagerPortClient
    Inherits System.ServiceModel.ClientBase(Of WSLayoutFacturacionModerna.Timbrado_ManagerPort)
    Implements WSLayoutFacturacionModerna.Timbrado_ManagerPort

    Public Sub New()
      MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
      MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
      MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
      MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
      MyBase.New(binding, remoteAddress)
    End Sub

    Public Function requestTimbrarCFDI(ByVal request As RequestTimbrarCFDI) As Object Implements WSLayoutFacturacionModerna.Timbrado_ManagerPort.requestTimbrarCFDI
      Return MyBase.Channel.requestTimbrarCFDI(request)
    End Function

    Public Function requestCancelarCFDI(ByVal request As RequestCancelarCFDI) As Object Implements WSLayoutFacturacionModerna.Timbrado_ManagerPort.requestCancelarCFDI
      Return MyBase.Channel.requestCancelarCFDI(request)
    End Function
  End Class
End Namespace
