'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Imports System.IO

Namespace WSLayoutFacturacionModerna
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://t2demo.facturacionmoderna.com/timbrado/soap", ConfigurationName:="WSLayoutFacturacionModerna.Timbrado_ManagerPort")>  _
    Public Interface Timbrado_ManagerPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="https://t2demo.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=True, Use:=System.ServiceModel.OperationFormatUse.Encoded)> _
        Function requestTimbrarCFDI(ByVal request As RequestTimbrarCFDI) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> Object

        <System.ServiceModel.OperationContractAttribute(Action:="https://t2demo.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction:="*"), _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=True, Use:=System.ServiceModel.OperationFormatUse.Encoded)> _
        Function requestCancelarCFDI(ByVal request As RequestCancelarCFDI) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Public Interface Timbrado_ManagerPortChannel
        Inherits WSLayoutFacturacionModerna.Timbrado_ManagerPort, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")> _
    Partial Public Class Timbrado_ManagerPortClient
        Inherits System.ServiceModel.ClientBase(Of WSLayoutFacturacionModerna.Timbrado_ManagerPort)
        Implements WSLayoutFacturacionModerna.Timbrado_ManagerPort

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        Public Function requestTimbrarCFDI(ByVal request As RequestTimbrarCFDI) As Object Implements WSLayoutFacturacionModerna.Timbrado_ManagerPort.requestTimbrarCFDI
            Dim objResponse As Object
            Try
                Return MyBase.Channel.requestTimbrarCFDI(request)
            Catch soapFault As System.ServiceModel.FaultException 'Manejo de soapFault
                Console.WriteLine("[" + soapFault.Code.Name + "] " + soapFault.Message)
                objResponse = Nothing
                Return objResponse
            End Try

        End Function

        Public Function requestCancelarCFDI(ByVal request As RequestCancelarCFDI) As String Implements WSLayoutFacturacionModerna.Timbrado_ManagerPort.requestCancelarCFDI            
            Try
                Return MyBase.Channel.requestCancelarCFDI(request)
            Catch soapFault As System.ServiceModel.FaultException 'Manejo de soapFault
                Console.WriteLine("[" + soapFault.Code.Name + "] " + soapFault.Message)
                Return ""
            End Try
        End Function
    End Class
End Namespace
